name: denhamparry
favicon: null
layout_spectrum: 0.35730439331382513
typography_spectrum: 0.004277542466297746
title: The life and times of Lewis Denham-Parry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17031401908025146
  lightness: 0.9542086191941053
  saturation: 0.2970946382265538
  rhythmicContrast: 0.9664701644796878
purpose: []
